name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - v2-swa
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - v2-swa

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build website
        run: |
          yarn install
          yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1
          yarn bootstrap
          yarn workspace typescriptlang-org setup-playground-cache-bust
          yarn build
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore
      -  name: Run unit tests
         run: |
           yarn build-site
           cp -r packages/typescriptlang-org/public site
         env:
          YARN_CHECKSUM_BEHAVIOR: ignore
      -  name: Generate site
         run: |
           yarn build-site
           cp -r packages/typescriptlang-org/public site
         env:
          YARN_CHECKSUM_BEHAVIOR: ignore
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_04D78E310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "site" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
      - name: Run Playwright tests
        run: |
          cd playwright-tests
          npm i
          npx playwright install-deps
          npx playwright install
          npx playwright test --reporter=line
        env:
          BASE_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_04D78E310 }}
          action: "close"
